version: "2"
services:
  node:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "npm start"

